### ISSUE TITLE
unable to download from London?

### ISSUE THREAD

**Issue by felixgeen** [retroplasma/flyover-reverse-engineering#8]
Hey retroplasma,

Im trying to use this tool again to rip some more stuff from Apple maps. I updated all the files from github and ran the default Santa Monica Pier example and it works fine. But when I try and run a location in London it fails with this error:
```

Felixs-MBP:flyover-reverse-engineering felix$ go run cmd/export-obj/main.go 51.488287 -0.316545 20 3 15
london 42193.4 51.49416405580992 -0.1312690762721167
panic: t must be 1 goroutine 1 [running]:
runtime/debug.Stack(0xc00011c9f0, 0x13a94c0, 0x14b4840)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/retroplasma/flyover-reverse-engineering/pkg/fly/c3mm.Parse.func1(0xc00011cde8)
	/Users/felix/go/src/github.com/retroplasma/flyover-reverse-engineering/pkg/fly/c3mm/c3mm.go:27 +0x5a
panic(0x13a94c0, 0x14b4840)
	/usr/local/Cellar/go/1.13.1/libexec/src/runtime/panic.go:679 +0x1b2
github.com/retroplasma/flyover-reverse-engineering/pkg/fly/c3mm.parseC3MMv1(0xc000362000, 0x12db5, 0x12fb5, 0x0, 0x3, 0x3f80000000000001, 0x3fcf81e7, 0x12d9a, 0x28bbd, 0xc0000c0060, ...)
	/Users/felix/go/src/github.com/retroplasma/flyover-reverse-engineering/pkg/fly/c3mm/c3mm.go:140 +0x958
github.com/retroplasma/flyover-reverse-engineering/pkg/fly/c3mm.parseC3MM(0xc000362000, 0x12db5, 0x12fb5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/felix/go/src/github.com/retroplasma/flyover-reverse-engineering/pkg/fly/c3mm/c3mm.go:42 +0xc3
github.com/retroplasma/flyover-reverse-engineering/pkg/fly/c3mm.Parse(0xc000362000, 0x12db5, 0x12fb5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/felix/go/src/github.com/retroplasma/flyover-reverse-engineering/pkg/fly/c3mm/c3mm.go:31 +0xca
main.(*context)._getC3mm(0xc0000b29c0, 0x0, 0x0, 0xc0002dd620, 0x7, 0xc0002dd7c8, 0x6, 0x3fecc280117a4a70, 0xbf62c4bce9e16431, 0x40e49a2ccccccccd, ...)
	/Users/felix/go/src/github.com/retroplasma/flyover-reverse-engineering/cmd/export-obj/main.go:315 +0x66b
main.(*context).getC3mm(0xc0000b29c0, 0x0, 0x0, 0xc0002dd620, 0x7, 0xc0002dd7c8, 0x6, 0x3fecc280117a4a70, 0xbf62c4bce9e16431, 0x40e49a2ccccccccd, ...)
	/Users/felix/go/src/github.com/retroplasma/flyover-reverse-engineering/cmd/export-obj/main.go:295 +0x117
main.(*context).checkTile(0xc0000b29c0, 0x0, 0x0, 0xc0002dd620, 0x7, 0xc0002dd7c8, 0x6, 0x3fecc280117a4a70, 0xbf62c4bce9e16431, 0x40e49a2ccccccccd, ...)
	/Users/felix/go/src/github.com/retroplasma/flyover-reverse-engineering/cmd/export-obj/main.go:189 +0x79
main.main()
	/Users/felix/go/src/github.com/retroplasma/flyover-reverse-engineering/cmd/export-obj/main.go:154 +0xd3e



goroutine 1 [running]:
main.main()
	/Users/felix/go/src/github.com/retroplasma/flyover-reverse-engineering/cmd/export-obj/main.go:156 +0x1460
exit status 2

```

any idea what it could be?

Thanks a lot dude!

**Comment by retroplasma** [comment]
Hey,

damn :) There are two issues:
1) London doesn't work anymore. Good find! I pushed a hotfix that disables C3MM to make it work. Checkout the branch "london-hotfix". Will need to look into it properly though.
2) Looks like there's no 3D data at 51.488287 -0.316545. Apple Maps shows flatland there. These coordinates won't work even with the hotfix, but other parts of London should.

**Comment by retroplasma** [comment]
Pushed proper fix https://github.com/retroplasma/flyover-reverse-engineering/commit/2a45fe8242f5cb19afa40b551a4f0a5bdd4b146d

**Comment by retroplasma** [comment]
Pushed proper fix https://github.com/retroplasma/flyover-reverse-engineering/commit/7ded41a1ebcccb8032a6140f6eb5ae772d5ee193

**Comment by felixgeen** [comment]
Thanks retroplasma! you rule
