### ISSUE TITLE
"x509: certificate signed by unknown authority" on WSL and missing src folder with Go 1.16

### ISSUE THREAD

**Issue by devingDev** [retroplasma/flyover-reverse-engineering#9]
```
go run cmd/export-obj/main.go 34.007603 -118.499741 20 3 40
panic: Get https://gspe35-ssl.ls.apple.com/geo_manifest/dynamic/config?application=geod&application_version=1&country_code=US&hardware=MacBookPro11,2&os=osx&os_build=20B29&os_version=11.0.1: x509: certificate signed by unknown authority

goroutine 1 [running]:
github.com/retroplasma/flyover-reverse-engineering/pkg/oth.CheckPanic(...)
        /home/bizz/go/src/github.com/retroplasma/flyover-reverse-engineering/pkg/oth/oth.go:36
main.main()
        /home/bizz/go/src/github.com/retroplasma/flyover-reverse-engineering/cmd/export-obj/main.go:105 +0x14a6
exit status 2
```

and when I comment out that checkpanic line:

```
go run cmd/export-obj/main.go 34.007603 -118.499741 20 3 40
panic: minPlace not found

goroutine 1 [running]:
github.com/retroplasma/flyover-reverse-engineering/pkg/oth.CheckPanic(...)
        /home/bizz/go/src/github.com/retroplasma/flyover-reverse-engineering/pkg/oth/oth.go:36
main.main()
        /home/bizz/go/src/github.com/retroplasma/flyover-reverse-engineering/cmd/export-obj/main.go:111 +0x1453
exit status 2
```

Please could you help me?

I really wanted to play around with this data..

**Comment by devingDev** [comment]
I tried installing newer go since WSL go was 1.12 or 1.13 .
So now I got 1.16 but when I do 
go get -d github.com/retroplasma/flyover-reverse-engineering/...
the ~/go/src/ folder does not exist.
There is only a pkg folder inside ~/go/ 

![image](https://user-images.githubusercontent.com/17065236/108198669-32c92c80-711c-11eb-92a5-26319ff742e1.png)

**Comment by devingDev** [comment]
Tried with older version 1.15 and it worked for the src folder part but it again gave me the x509 Error


```
go run cmd/export-obj/main.go 34.007603 -118.499741 20 3 40
panic: Get "https://gspe35-ssl.ls.apple.com/geo_manifest/dynamic/config?application=geod&application_version=1&country_code=US&hardware=MacBookPro11,2&os=osx&os_build=20B29&os_version=11.0.1": x509: certificate signed by unknown authority

goroutine 1 [running]:
github.com/retroplasma/flyover-reverse-engineering/pkg/oth.CheckPanic(...)
        /home/bizzy/go/src/github.com/retroplasma/flyover-reverse-engineering/pkg/oth/oth.go:36
main.main()
        /home/bizzy/go/src/github.com/retroplasma/flyover-reverse-engineering/cmd/export-obj/main.go:105 +0x14b3
exit status 2
```

Which version do you use maybe I can fix it by using that?

**Comment by retroplasma** [comment]
I'm using Go 1.15.

Hmm, last time I checked WSL was working, but I can't test on WSL atm. About that `x509: certificate signed by unknown authority` message, maybe some certificates are missing on WSL which are used for https://gspe35-ssl.ls.apple.com. Maybe this helps https://github.com/microsoft/WSL/issues/3161 and see if this command runs: `openssl s_client -showcerts -verify 32 -connect gspe35-ssl.ls.apple.com:443` or `curl https://gspe35-ssl.ls.apple.com`.

**Comment by retroplasma** [comment]
Will look into 1.16 when I can. Looks like there are some changes regarding go modules which might be the reason for the missing src folder.

**Comment by devingDev** [comment]
I tried doing what they said in that thread as far as I understood but its not detailed enough for me to understand.

This comment is what I tried

https://github.com/microsoft/WSL/issues/3161#issuecomment-451863149

Idk what to do for the first one he says placing some crt somewhere but i dont have that crt file?
https://github.com/microsoft/WSL/issues/3161#issue-320777324

**Comment by devingDev** [comment]
$ curl https://gspe35-ssl.ls.apple.com
curl: (60) SSL certificate problem: unable to get local issuer certificate

**Comment by devingDev** [comment]
```
$ openssl s_client -showcerts -verify 32 -connect gspe35-ssl.ls.apple.com:443
verify depth is 32
CONNECTED(00000003)
depth=1 CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = gspa35-ssl.ls.apple.com, OU = management:idms.group.1208920, O = Apple Inc., ST = California, C = US
verify return:1
---
Certificate chain
 0 s:CN = gspa35-ssl.ls.apple.com, OU = management:idms.group.1208920, O = Apple Inc., ST = California, C = US
   i:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
-----BEGIN CERTIFICATE-----
MIIIwzCCB6ugAwIBAgIQXDsS73M9v7e+O871+gKOtjANBgkqhkiG9w0BAQsFADBi
MRwwGgYDVQQDExNBcHBsZSBJU1QgQ0EgMiAtIEcxMSAwHgYDVQQLExdDZXJ0aWZp
Y2F0aW9uIEF1dGhvcml0eTETMBEGA1UEChMKQXBwbGUgSW5jLjELMAkGA1UEBhMC
VVMwHhcNMTkwMzA4MDU0NTE3WhcNMjEwNDA2MDU0NTE3WjCBgTEgMB4GA1UEAwwX
Z3NwYTM1LXNzbC5scy5hcHBsZS5jb20xJjAkBgNVBAsMHW1hbmFnZW1lbnQ6aWRt
cy5ncm91cC4xMjA4OTIwMRMwEQYDVQQKDApBcHBsZSBJbmMuMRMwEQYDVQQIDApD
YWxpZm9ybmlhMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAMSbs+SXzuwB0a9aEevN9zYtWyR4JOJTzDlt4OpUCSrJ6CgFzyYGhIhB
skcqFj9DabdE9XlkTxmK9XXHpXKbPyMgTW60rTKsMHmrbPRsWnihUs1jx5j0koHw
RJxYh9ZBcNJn96RGggmbozqF026jqwDvFpt5CBDAYhUe/rUEgMVXIc5Loke4m5Jl
Ye1QU+w/+fnsA8ISWWo280S/NgUkbQcytTQ9Y1kHuomWjqmKK0w/dn6COxYNBvJL
H9jxJ7yDAvDnR2XAQonbgyOcsosViRS3t06tNWaJVEBAmzGTsJNHql12yxaLpUE4
p7yHn1ikzrp7jGewRpqI+A+j0ZIe590CAwEAAaOCBVMwggVPMAwGA1UdEwEB/wQC
MAAwHwYDVR0jBBgwFoAU2HqURHyQcJAWnt0XnAFEA4bWKikwfgYIKwYBBQUHAQEE
cjBwMDQGCCsGAQUFBzAChihodHRwOi8vY2VydHMuYXBwbGUuY29tL2FwcGxlaXN0
Y2EyZzEuZGVyMDgGCCsGAQUFBzABhixodHRwOi8vb2NzcC5hcHBsZS5jb20vb2Nz
cDAzLWFwcGxlaXN0Y2EyZzEyMDCBpgYDVR0RBIGeMIGbghpnc3BhMzUta3Itc3Ns
LmxzLmFwcGxlLmNvbYIXZ3NwYTM1LXNzbC5scy5hcHBsZS5jb22CFmdzcGUxLXNz
bC5scy5hcHBsZS5jb22CF2dzcGUyMS1zc2wubHMuYXBwbGUuY29tghpnc3BlMzUt
a3Itc3NsLmxzLmFwcGxlLmNvbYIXZ3NwZTM1LXNzbC5scy5hcHBsZS5jb20wgf8G
A1UdIASB9zCB9DCB8QYKKoZIhvdjZAULBDCB4jCBpAYIKwYBBQUHAgIwgZcMgZRS
ZWxpYW5jZSBvbiB0aGlzIGNlcnRpZmljYXRlIGJ5IGFueSBwYXJ0eSBhc3N1bWVz
IGFjY2VwdGFuY2Ugb2YgYW55IGFwcGxpY2FibGUgdGVybXMgYW5kIGNvbmRpdGlv
bnMgb2YgdXNlIGFuZC9vciBjZXJ0aWZpY2F0aW9uIHByYWN0aWNlIHN0YXRlbWVu
dHMuMDkGCCsGAQUFBwIBFi1odHRwOi8vd3d3LmFwcGxlLmNvbS9jZXJ0aWZpY2F0
ZWF1dGhvcml0eS9ycGEwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMDcG
A1UdHwQwMC4wLKAqoCiGJmh0dHA6Ly9jcmwuYXBwbGUuY29tL2FwcGxlaXN0Y2Ey
ZzEuY3JsMB0GA1UdDgQWBBSVFiRHPigtzxv2Yy6KMnhpKPH1hTAOBgNVHQ8BAf8E
BAMCBaAwggJqBgorBgEEAdZ5AgQCBIICWgSCAlYCVAB1ALvZ37wfinG1k5Qjl6qS
e0c4V5UKq1LoGpCWZDaOHtGFAAABaVveu7kAAAQDAEYwRAIgGjcoEK6bLYU+lSYc
wYUv2XcZfU7mfA1Noh3PMQFtT88CIEarpdeVDslgRcUaJxlHjvbUsgL9jyDBmTCN
KdYA+bg3AHUApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN3BAAAAFpW967
wQAABAMARjBEAiAlkDgf+M5Y3e944A3X/seBtjA8lK+lf4/lLAzBcXvUvgIgLBN0
VOHtN8FW3LgH1VASWRk9Wmnd1L0JpLioa+tX4IUAdQBWFAaaL9fC7NP14b1Esj7H
Rna5vJkRXMDvlJhV1onQ3QAAAWlb3rynAAAEAwBGMEQCIAU4We2Bkm6vgYm/kzLX
DeFV82HrVstongHV99QGfmOZAiBaMvw4HQuw7L0WoZcazV/xFqMs/UIm1NLgkPLo
xVrwyAB2APZclC/RdzAiFFQYCDCUVo7jTRMZM7/fDC8gC8xO8WTjAAABaVveu+EA
AAQDAEcwRQIgO1CUxDpPw6Pi63VAQFTw8YkwBq11ut2z0cYP2qK43HMCIQCc+qvu
qL9waaEKdpBpYgSAou1dlbQcvtgVRGoFcplBHgB1AId1v+dZfPiMQ5lfvfNu/1aN
R1Y2/0q1YMG06v9eoIMPAAABaVvevIMAAAQDAEYwRAIgL1nGDJW/cH3ClGb1eSEU
eyUsAIQdt5YVXExWU86qQ24CIHlT5qedxYJcIgbFA8NOxvEhh4+vgprjcmsLeNIK
pvZqMA0GCSqGSIb3DQEBCwUAA4IBAQC2C/YhERG+32dJK5YMJWC/QYJUNUDgGfKn
5Kp/pLLqCrQKv+s9sfOW5JJbXsiPMV6XZQhzRmiTNfvdjQZzWH5E0foWmWIO9V2t
0Ndy9Bj7M+e47LB1flaEj2NCb87i1c30Unf7mQtoqe9FUv4XNRr4/Q5YV8PEcm94
c0W7SHdfV8EZX6d2GuzqXDY8/TbqYvHTeV7IuTCKDIebP4LPxr+WmcAjFUNj+tmG
9i4VWHsgsQZuUM/jSZA72R1Q4Z8bxPUw9hxeTanS6mm+DRwhVrnpkBhWIK0Uh9Nt
BgqwcRvzoNkNizLmUh6M6lJ0Ra8bl4XboJ3BvNLxf/04dwE4mq6G
-----END CERTIFICATE-----
 1 s:CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US
   i:C = US, O = GeoTrust Inc., CN = GeoTrust Global CA
-----BEGIN CERTIFICATE-----
MIIEQDCCAyigAwIBAgIDAjp0MA0GCSqGSIb3DQEBCwUAMEIxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i
YWwgQ0EwHhcNMTQwNjE2MTU0MjAyWhcNMjIwNTIwMTU0MjAyWjBiMRwwGgYDVQQD
ExNBcHBsZSBJU1QgQ0EgMiAtIEcxMSAwHgYDVQQLExdDZXJ0aWZpY2F0aW9uIEF1
dGhvcml0eTETMBEGA1UEChMKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDQk6EdR0MgFrILa+vD1bTox5jN896/
6E3p4zaAB/xFG2p8RYauVtOkCX9hDWtdflJrfbTIOcT0Zzr3g84Zb4YvfkV+Rxxn
UsqVBV3iNlGFwNRngDVvFd0+/R3S/Y80UNjsdiq+49Pa5P3I6ygClhGXF2Ec6cRZ
O0LcMtEJHdqm0UOG/16yvIzPZtsBiwKulEjzOI/96jKoCOyGl1GUJD5JSZZT6Hmh
QIHpBbuTlVH84/18EUv3ngizFUkVB/nRN6CbSzL2tcTcatH8Cu324MUpoKiLcf4N
krz+VHAYCm3H7Qz7yS0Gw4yF/MuGXNY2jhKLCX/7GRo41fCUMHoPpozzAgMBAAGj
ggEdMIIBGTAfBgNVHSMEGDAWgBTAephojYn7qwVkDBF9qn1luMrMTjAdBgNVHQ4E
FgQU2HqURHyQcJAWnt0XnAFEA4bWKikwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNV
HQ8BAf8EBAMCAQYwNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2cuc3ltY2IuY29t
L2NybHMvZ3RnbG9iYWwuY3JsMC4GCCsGAQUFBwEBBCIwIDAeBggrBgEFBQcwAYYS
aHR0cDovL2cuc3ltY2QuY29tMEwGA1UdIARFMEMwQQYKYIZIAYb4RQEHNjAzMDEG
CCsGAQUFBwIBFiVodHRwOi8vd3d3Lmdlb3RydXN0LmNvbS9yZXNvdXJjZXMvY3Bz
MA0GCSqGSIb3DQEBCwUAA4IBAQAWR3NvhaJi4ecqdruJlUIml7xKrKxwUzo/MYM9
PByrmuKxXRx2GqA8DHJXvtOeUODImdZY1wLqzg0pVHzN9cLGkClVo28UqAtCDTqY
bQZ4nvBqox0CCqIopI3CgUY+bWfa3j/+hQ5CKhLetbf7uBunlux3n+zUU5V6/wf0
8goUwFFSsdaOUAsamVy8C8m97e34XsFW201+I6QRoSzUGwWa5BtS9nw4mQVLunKN
QolgBGYq9P1o12v3mUEo1mwkq+YlUy7Igpnioo8jvjCDsSeL+mh/AUnoxphrEC6Y
XorXykuxx8lYmtA225aV7LaB5PLNbxt5h0wQPInkTfpU3Kqm
-----END CERTIFICATE-----
---
Server certificate
subject=CN = gspa35-ssl.ls.apple.com, OU = management:idms.group.1208920, O = Apple Inc., ST = California, C = US

issuer=CN = Apple IST CA 2 - G1, OU = Certification Authority, O = Apple Inc., C = US

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3914 bytes and written 395 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 20 (unable to get local issuer certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 5B338845617776334A4B00687F669654172DC45BE990C257CA06A8A19DE1BC38
    Session-ID-ctx:
    Resumption PSK: FED58BA39A72AAE5AF6B185285DB93EB0F75E177034F029AD0A064B1532C29C9FA52A758E13E04161C9FE1A8712F8E4A
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 83100 (seconds)
    TLS session ticket:
    0000 - 00 00 1b 4b 68 f7 13 2b-35 f2 f4 c6 50 25 ee 18   ...Kh..+5...P%..
    0010 - 6d 2d 51 00 e2 a5 a9 d0-2a 76 1a 7e 3a a5 a0 b5   m-Q.....*v.~:...
    0020 - e3 3d 76 0c 53 61 00 6f-de 7c 08 54 7a 40 f4 63   .=v.Sa.o.|.Tz@.c
    0030 - 59 f4 25 3f ca 70 d2 3b-fc 83 5e 7f 17 eb 2e ae   Y.%?.p.;..^.....
    0040 - f3 1a 68 a3 a9 26 99 53-4a 1f f0 71 05 0a c6 53   ..h..&.SJ..q...S
    0050 - ee 00 98 de 7b e8 97 7c-9e dd ef 30 99 91 a6 ee   ....{..|...0....
    0060 - 3c 27 5d 1e 9f 7c e1 2b-cf 9b dc bb 2d 9c 50 db   <']..|.+....-.P.
    0070 - c3 5b a5 6c 86 13 ef dd-9e a2 88 4a 88 2e 4d eb   .[.l.......J..M.
    0080 - f3 7b c5 7b d2 11 07 0e-a1 eb 7c a0 c0 ad 8d 5e   .{.{......|....^
    0090 - eb 21 09 35 1b 49 8f 21-6a 84 37 03 4c 78 19 84   .!.5.I.!j.7.Lx..
    00a0 - 61 b9 13 58 ac cb 97 de-1c 9c 2a e2 df 26 56 20   a..X......*..&V
    00b0 - e5 31 fe ed a7 d2 61 74-9c df ef e5 9d f7 ba 72   .1....at.......r
    00c0 - d1 44 4b f0 fd 40 99 97-20 fa 54 20 81 c5 50 94   .DK..@.. .T ..P.
    00d0 - 61 73 34 d2 8b 68 ba 36-ef d6 f2 26 04 a0 b4 2d   as4..h.6...&...-
    00e0 - 26 9e e2 ad 18 36 5d 61-2e f7 1c bf 79 07 59 3f   &....6]a....y.Y?

    Start Time: 1613596238
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: E3E056088E5DD557C2BC0A22FE7564B1E16B4103C43621F664D360FEB1C745CF
    Session-ID-ctx:
    Resumption PSK: 0EDFCCDF89E4B880A2FCE0A61C5709D45558E1A3698A55ECDEB43D5315A96A01E7096191FC5A8E4491329A10DD446EF4
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 83100 (seconds)
    TLS session ticket:
    0000 - 00 00 1b 4b 68 f7 13 2b-35 f2 f4 c6 50 25 ee 18   ...Kh..+5...P%..
    0010 - e9 87 99 f7 c9 6c ae c5-ab f5 3e 54 28 11 02 ac   .....l....>T(...
    0020 - 0a d7 30 7c 3e 0f 15 4c-98 a6 6d 12 bb f8 9a 84   ..0|>..L..m.....
    0030 - b7 80 43 73 29 e9 c1 01-4a da 0b a6 e4 ad 3f 50   ..Cs)...J.....?P
    0040 - 89 96 57 b5 c3 82 cf fd-c8 a0 82 88 c6 c8 b4 9a   ..W.............
    0050 - a7 f4 e9 49 c2 17 f4 d8-7a 34 64 60 af 8c f1 a3   ...I....z4d`....
    0060 - 12 d0 ac 94 d1 52 06 63-36 66 c0 eb cb 35 ca d5   .....R.c6f...5..
    0070 - e6 a3 fc c5 8e a7 82 a3-80 a4 dc 78 ac dc 8a e9   ...........x....
    0080 - db 1a ca 3e cf ed 54 d2-29 d2 ba be 4e 2c 97 c4   ...>..T.)...N,..
    0090 - 13 be 49 51 1b c9 3f d7-59 cb 2a 72 cd 0e e4 cd   ..IQ..?.Y.*r....
    00a0 - 09 56 65 f2 33 e7 19 88-74 22 b1 c5 8f 7e 1f 4b   .Ve.3...t"...~.K
    00b0 - f0 75 80 fb cb 9c f3 fe-a5 4b e5 08 39 2c be 54   .u.......K..9,.T
    00c0 - fa 60 a0 7c 5f 8c ce d9-26 39 ea e7 64 48 43 5f   .`.|_...&9..dHC_
    00d0 - 20 39 01 2b b4 01 cb d6-04 c4 13 7d 16 f6 17 9f    9.+.......}....
    00e0 - 1a e7 53 51 96 de 56 55-5e 3e 7e dc d1 48 ff 46   ..SQ..VU^>~..H.F

    Start Time: 1613596238
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
closed
```

**Comment by retroplasma** [comment]
Hm, it works on a friend's WSL. I don't know how yours is set up. See if you can access the URL in a browser without any cert errors. I think browsers can export those certs. A *.crt file starts with `-----BEGIN CERTIFICATE-----` and ends with `-----END CERTIFICATE-----` like those in your openssl output; you can try to put the ones from that output into some *.crt files. Or you can go yolo and disable verification in Go ([like this](https://stackoverflow.com/questions/12122159/how-to-do-a-https-request-with-bad-certificate)). Can't tell for sure what's going on here though 🤔.

**Comment by devingDev** [comment]
I went to the site you mentioned and it gave me some 403 Forbidden text in the html.
In firefox I pressed save cert and cert chain which were .pem files which i converted to crt somehow and tried installing via update certificates command in wsl. they are in /etc/ssl/ something but it still gives me that x509 error.
gonna try disabling it now idk how but I'll try

**Comment by devingDev** [comment]
Added that to the main.go
```
http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
  
```

Seems to work?

```
$ go run cmd/export-obj/main.go 34.007603 -118.499741 20 3 40
Los Angeles 111026.8 33.88808567049225 -117.9332591170418
Exporting -3 -3 h = 0
Exporting -3 -2 h = 0
Exporting -3 -1 h = 0
Exporting -3 0 h = 0
Exporting -3 1 h = 0
Exporting -3 2 h = 0
Exporting -3 3 h = 0
Exporting -2 -3 h = 0
Exporting -2 -2 h = 0
Exporting -2 -1 h = 0
Exporting -2 0 h = 0
Exporting -2 1 h = 0
Exporting -2 2 h = 0
Exporting -2 3 h = 0
Exporting -1 -3 h = 0
Exporting -1 -2 h = 0
Exporting -1 -1 h = 0
Exporting -1 0 h = 0
Exporting -1 1 h = 0
Exporting -1 2 h = 0
Exporting -1 3 h = 0
Exporting 0 -3 h = 0
Exporting 0 -2 h = 0
Exporting 0 -1 h = 0
Exporting 0 0 h = 0
Exporting 0 1 h = 0
Exporting 0 2 h = 0
Exporting 0 3 h = 0
Exporting 1 -3 h = 0
Exporting 1 -2 h = 0
Exporting 1 -1 h = 0
Exporting 1 0 h = 0
Exporting 1 1 h = 0
Exporting 1 2 h = 0
Exporting 1 3 h = 0
Exporting 2 -3 h = 0
Exporting 2 -2 h = 0
Exporting 2 -1 h = 0
Exporting 2 0 h = 0
Exporting 2 1 h = 0
Exporting 2 2 h = 0
Exporting 2 3 h = 0
Exporting 3 -3 h = 0
Exporting 3 -2 h = 0
Exporting 3 -1 h = 0
Exporting 3 0 h = 0
Exporting 3 1 h = 0
Exporting 3 2 h = 0
Exporting 3 3 h = 0
49 exported

 ```

**Comment by devingDev** [comment]
Any idea why my maps are weirdly rotated?
I followed this and ran the center scale script 
https://github.com/retroplasma/earth-reverse-engineering/blob/1dd24a723513d7e96f249e2c635416d4596992c4/BLENDER.md

![image](https://user-images.githubusercontent.com/17065236/108489906-69c94a80-72a2-11eb-9fb4-68a036b1b9f4.png)

Also it looks so bad in fps view damn.. just wanted to make a funny game
![image](https://user-images.githubusercontent.com/17065236/108491934-d7767600-72a4-11eb-8642-3da182e7f7cd.png)

**Comment by retroplasma** [comment]
Yup the script doesn't rotate it. You can try something like https://github.com/retroplasma/earth-reverse-engineering/issues/30 for rotation.

The whole thing is meant for bird's eye view so you won't get a pretty FPS. but u can tweak that shading so it's smooth and not showing the polygons

I'm closing this though since the export is working now
